### ISSUE TITLE
Combining Constants works in JS but not in Kotlin

### ISSUE THREAD

**Issue by thigg** [exaV/screeps-kotlin-types#44]
Bein able to combine e.g. FIND constants is a very useful feature:

    find(FIND_CONSTRUCTION_SITES | FIND_STRUCTURES,...)

I guess there is no nice solution to preserve typing, but mebe we should still make it available?

**Comment by Jomik** [comment]
Can you not do it with
```
find(FIND_CONSTRUCTION_SITES or FIND_STRUCTURES,...)
```

**Comment by thigg** [comment]
Ah I didn't try the or, just |. Maybe that should be documented somewhere?

**Comment by thigg** [comment]
No, I get a:  ` Unresolved reference: or` when I try:
`findInRange(FIND_MY_CONSTRUCTION_SITES or FIND_MY_STRUCTURES, 4 )`

**Comment by thigg** [comment]
Idea from @AWRyder : FIND_MY_CONSTRUCTION_SITES.value or  FIND_MY_STRUCTURES.value
seems to work. Will test.

**Comment by thigg** [comment]
It is compiled to

    var target = $receiver.pos.findClosestByPath(Kotlin.isType(tmp$ = FIND_MY_STRUCTURES | FIND_CREEPS, Object) ? tmp$ : throwCCE(), options(beTransporter$lambda));

Which looks good. the filter is not called however. Not sure if this is a fault of my code, or it doesn't work properly

**Comment by thigg** [comment]
While you can combine them in JS, this is no valid behavior after all. I think i dreamed of that function ;)

**Comment by thigg** [comment]
Wrote me a helper for this:

```
/*
 * Find with multiple flags
 */
fun RoomPosition.findClosestByPath(
        opts: FindClosestByPathOptions<RoomObject>,
        vararg types: FindConstant<RoomObject>
): RoomObject? {
    val objects: Array<RoomObject> = types.map { Game.rooms[this.roomName]?.find(it) }.foldRight(arrayOf<RoomObject>(), { l, r -> l!! + r })
    return findClosestByPath(objects, opts)
}
```
