### ISSUE TITLE
StructureTower.attack() not able to attack PowerCreep or Structure

### ISSUE THREAD

**Issue by WilhelmOks** [exaV/screeps-kotlin-types#49]
The screeps docs say that a tower can attack one of the three: Creep, PowerCreep, Structure.
https://docs.screeps.com/api/#StructureTower.attack

In the kotlin types however, the attack() function can only take a Creep as parameter.
I see no workaround here to be able to attack power-creeps or structures.

**Comment by exaV** [comment]
Fixed in 1.6.1 see a991360

**Comment by WilhelmOks** [comment]
Awesome work! Thanks.
