### ISSUE TITLE
Add Id to Flags

### ISSUE THREAD

**Issue by codedraughtsman** [exaV/screeps-kotlin-types#57]
Flags don't seem to have an id member.
The flag class looks like it is missing the `Identifiable` interface.

Could you please add it :)
Thank you.

**Comment by MaggNorway** [comment]
Flags do not have an ID in the api.

See https://docs.screeps.com/api/#Flag

**Comment by MaggNorway** [comment]
PS: There is a #kotlin Slack channel at Screeps Slack! Feel free to join and discuss things. :)

**Comment by codedraughtsman** [comment]
@MaggNorway thanks for that. I did not realise that they actually did not have IDs. 
I will look into joining the Slack channel :)
